POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3MjU2NjA0LCJ1c2VySWQiOjN9.DafCTX1f15PwA_ZUZKFs1UBygZhOYm3IC7nEsiuuZWc

{
    "name": "Test event 3",
    "description": "A test 3 event",
    "location": "A test 3 location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}