DELETE http://localhost:8080/events/6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTc2MTk2NjksInVzZXJJZCI6MX0.T4vQovEmA21vvQy9ALA30jRnx6lEWZOQysk6sbDxiF8
