DELETE http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3NjE0OTUzLCJ1c2VySWQiOjN9.Seo3MiJoiX6Hn4iDz86hWdIz6nBS4jX-sOMVL4O6Wjw
