POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3Njk3OTMxLCJ1c2VySWQiOjJ9.jMTpls1fKSuQmw85L_LdhG4211SqPTfG8rnNdDYaF5E